routes/admin.php
<?php


Route::group(array('namespace'=>'Admin','prefix' => 'admin'), function () {

	Route::get('/admin', function(){
		return redirect()->route('admin.login.get');
	});

	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

	Route::get('reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

	Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.reset');

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

	Route::post('/login-post', 'Auth\AdminLoginController@login')->name('admin.login.post');

	Route::group(['middleware' => ['admin']], function () {

		//route for dashboard
		Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
		//route for logout
		Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
		//route for change-password
	});

});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login.get');
});

// Route::get('admin/change-password',function(){
// 	return view('admin.changepassword');
// });
Route::get('admin/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\AdminLoginController@login')->name('admin.login');

Route::post('admin/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');
Route::get('admin/password/reset/{token?}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get('admin/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout');

Route::post('admin/password/reset-password', 'Admin\Auth\ResetPasswordController@reset')->name('password.reset.post.password');

Route::get('/products/export','Admin\ProductController@exceltoexport')->name('products.export');
Route::post('notifications/names','Admin\NotificationController@getName')->name('get.name.notification');
Route::post('banners/names','Admin\BannerController@getName')->name('get.name.banner');
Route::get('admin/category/categoryorder','Admin\CategoryController@CategoryOrder')->name('category.order.get');
Route::get('admin/brand/brandorder','Admin\BrandController@BrandOrder')->name('brand.order.get');
Route::get('admin/banner/bannerorder','Admin\BannerController@BannerOrder')->name('banner.order.get');
Route::get('admin/products/suggetion','Admin\ProductController@CollectionSuggetion')->name('products.collection.suggetion');
Route::get('admin/product/suggetion/{id}','Admin\ProductController@CollectionSuggetionEdit')->name('products.suggetion.update');

Route::get('dealer/reset','Admin\UserController@ResetApiViewFile')->name('dealer.reset');
Route::post('api/reset/password','Admin\UserController@ApiResetPassword')->name('dealer.reset.password');

Route::group(['namespace'=>'Admin','prefix'=>'admin','middleware'=>'admin'],function(){
Route::post('dealers/deactive/{id}','UserController@deActive')->name('dealers.deactive');
	Route::resource('/brands','BrandController');
	Route::post('brands/delete','BrandController@delete')->name('brands.delete');
	Route::post('brand/order','BrandController@Order')->name('brand.order');	

	Route::resource('/category','CategoryController');
	Route::post('category/delete','CategoryController@delete')->name('category.delete');
	Route::post('category/order','CategoryController@Order')->name('category.order');

	Route::resource('/products','ProductController',['except'=>'update']);
	Route::post('/products/delete','ProductController@delete')->name('products.delete');
	Route::post('/products/update/{id}','ProductController@update')->name('products.update');
	Route::post('/products/category','ProductController@getCategory')->name('products.getcategory');
	Route::post('/products/image','ProductController@deleteImage')->name('delete.image');
	Route::post('/products/multipleimage','ProductController@UploadImage')->name('upload.url');
	Route::post('/products/size','ProductController@getSize')->name('products.getsize');	

	Route::post('/orders/{id}','OrderController@update')->name('orders.update');
	Route::post('/orders/store/invoice','OrderController@invoiceStore')->name('orders.store.invoice');
	Route::get('/orders/cancel','OrderController@OrderCancel')->name('orders.cancel');

	Route::resource('/orders','OrderController',['except'=>'update']);
	Route::post('/orders/delete','OrderController@delete')->name('orders.delete');
	Route::post('/orders/store/city','OrderController@getCity')->name('orders.getcity');
	Route::post('/orders/store/shippingcity','OrderController@getShippingCity')->name('orders.shippingcity');
	Route::post('/orders/store/getproductdata', 'OrderController@getProductData')->name('orders.getproductdata');
	Route::post('/orders/store/getdealerdata', 'OrderController@getDealerData')->name('orders.getdealerdata');
	Route::post('/orders/store/size','OrderController@getSize')->name('orders.getsize');

	Route::post('/user-plan/store','UserPlanController@store')->name('user-plan.store');
	Route::post('/user-plan/update/{id}','UserPlanController@update')->name('user-plan.update');
	Route::resource('/user-plan','UserPlanController',['except'=>'store','update']);
	Route::post('/user-plan/delete','UserPlanController@delete')->name('user-plan.delete');
	Route::post('/user-plan/category','UserPlanController@getCategory')->name('user-plan.getcategory');
	Route::post('/user-plan/product','UserPlanController@getProduct')->name('user-plan.getproduct');

	Route::resource('/coupons','CoupanCodeController');
	Route::post('/coupons/delete','CoupanCodeController@delete')->name('coupons.delete');
	// Route::post('/coupans/category','CoupanCode@getCategory')->name('coupans.getcategory');

	Route::resource('/color','ColorController');
	Route::post('color/delete','ColorController@delete')->name('color.delete');

	Route::resource('/size','SizeController');
	Route::post('size/delete','SizeController@delete')->name('size.delete');

	Route::resource('/pages','StaticPageController');
	Route::post('pages/delete','StaticPageController@delete')->name('pages.delete');


	Route::resource('/shipment','ShipmentController');
	Route::post('shipment/delete','ShipmentController@delete')->name('shipment.delete');

	Route::resource('/notifications','NotificationController');
	Route::post('notifications/delete','NotificationController@delete')->name('notifications.delete');

	Route::resource('/banners','BannerController');
	Route::post('banner/order','BannerController@Order')->name('banner.order');	
	Route::post('banners/delete','BannerController@delete')->name('banners.delete');
	

	Route::get('/dealers/view/{id}','UserController@view')->name('dealers.view');
	Route::resource('/dealers','UserController',['except'=>'show']);

	Route::get('/pdf','PdfController@downloadpdf')->name('pdf.get');

	Route::resource('/sales-person','SalesPersonController');
	Route::post('/sales-person/delete','SalesPersonController@delete')->name('sales-person.delete');
	Route::resource('/reports','ReportController');

	Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth:admin']], function () {

			Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
			Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
	});
});

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    protected $table = "notifications";
    protected $fillable = ['id','title','description','type','name','status','action_id','image'];

    public function getImageAttribute($value){
    	return LOCAL_IMAGE_PATH.'notification/'.$value;
    }
}

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB,Form;
use App\Models\Notification;
use App\Events\NotificationEvent;
use App\Http\Requests\NotificationRequest;
use Event;
use App\Models\Product;
use App\Models\Brand;
use App\Models\Category;

class NotificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            $where_str    = "1 = ?";
            $where_params = array(1); 

            if (!empty($request->input('sSearch')))
            {
                $search     = $request->input('sSearch');
                $where_str .= " and (id like \"%{$search}%\""
                . " or title like \"%{$search}%\""
                . " or type like \"%{$search}%\""
                . " or status like \"%{$search}%\""
                . ")";
            }

            $columns = ['id','updated_at','title','description','type','image','status','action_id'];

            $companymaster_columns_count = Notification::select($columns)
            ->whereRaw($where_str, $where_params)
            ->count();

            $companymaster_list = Notification::select($columns)
            ->whereRaw($where_str, $where_params);

            if($request->get('iDisplayStart') != '' && $request->get('iDisplayLength') != ''){
                $companymaster_list = $companymaster_list->take($request->input('iDisplayLength'))
                ->skip($request->input('iDisplayStart'));
            }

            if($request->input('iSortCol_0')){
                $sql_order='';
                for ( $i = 0; $i < $request->input('iSortingCols'); $i++ )
                {
                    $column = $columns[$request->input('iSortCol_' . $i)];
                    if(false !== ($index = strpos($column, ' as '))){
                        $column = substr($column, 0, $index);
                    }
                    $companymaster_list = $companymaster_list->orderBy($column,$request->input('sSortDir_'.$i));   
                }
            } 


            $companymaster_list = $companymaster_list->get();

            $response['iTotalDisplayRecords'] = $companymaster_columns_count;
            $response['iTotalRecords'] = $companymaster_columns_count;
            $response['sEcho'] = intval($request->input('sEcho'));
            $response['aaData'] = $companymaster_list->toArray();

            return $response;
        }
        return view('admin.notification.index');
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $notification = [];
        // dd(old('type'));
        if((old('type')) == 'product')
        {
            // dd(old('type'));
            $notification = (old('type')) ? [""=>"Select Product"] + Product::pluck("name","id")->toArray() :["" =>"Select Product"] + Product::pluck('name', 'id')->toArray();
            // dd($notification);
        }
        elseif (old('type') == 'brand') 
        {
            $notification = (old('type')) ? [""=>"Select Brand"] + Brand::pluck("name","id")->toArray() :["" =>"Select Brand"] + Brand::pluck('name', 'id')->toArray();
        }
        else
        {
            $notification = (old('type')) ? [""=>"Select Category"] + Category::pluck("name","id")->toArray() :["" =>"Select Category"] + Category::pluck('name', 'id')->toArray();
        }
        return view('admin.notification.create',compact('notification'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NotificationRequest $request)
    {
        $notification_data = $request->all();
       // dd($notification_data);
        $notification_data['title'] = strip_tags($request->title);
        Event::fire(new NotificationEvent($notification_data));

        if($request->save_button == 'save_new') 
        {
            return back()->with('message','Record added  Successfully')
            ->with('message_type','success');
        }
        return redirect()->route('notifications.index')->with('message','Record added Successfully')->with('message_type','success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $notification_data = Notification::find($id);
        $notification_image = explode('/', $notification_data['image']);
        //dd($notification_image[5]);
        $id = $notification_data['id'];
        $type = $notification_data['type'];
        $notification = [];
        // dd(old('type'));
        if((old('type')) == 'product')
        {
            // dd(old('type'));
            $notification = (old('type')) ? [""=>"Select Product"] + Product::pluck("name","id")->toArray() :["" =>"Select Product"] + Product::pluck('name', 'id')->toArray();
            // dd($notification);
        }
        elseif (old('type') == 'brand') 
        {
            $notification = (old('type')) ? [""=>"Select Brand"] + Brand::pluck("name","id")->toArray() :["" =>"Select Brand"] + Brand::pluck('name', 'id')->toArray();
        }
        else
        {
            $notification = (old('type')) ? [""=>"Select Category"] + Category::pluck("name","id")->toArray() :["" =>"Select Category"] + Category::pluck('name', 'id')->toArray();
        }
        //dd($notification);
        return view('admin.notification.edit',compact('notification_data','id','notification','notification_image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NotificationRequest $request, $id)
    {
        $notification_data = $request->all();
        //dd($notification_data);
        $notification_data['id'] = $id;
        //dd($notification_data);
        $notification_data['title'] = strip_tags($request->title);
        Event::fire(new NotificationEvent($notification_data));

        if($request->save_button == 'save_new') 
        {
            return back()->with('message','Record Updated  Successfully')
            ->with('message_type','success');
        }
        return redirect()->route('notifications.index')->with('message','Record Updated Successfully')->with('message_type','success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    
    public function delete(Request $request)
    {
        $notification_id = $request->get('id');

        if(is_array($notification_id)){
            foreach ($notification_id as $key => $value) {
                Notification::where('id', $value)->delete();
            }
        }
        else{
            Notification::where('id', $notification_id)->delete();
        }    
        return back()->with('message', 'Record deleted Successfully.')
        ->with('message_type', 'success');
    }

    public function getName(Request $request)
    {
        $type = $request->get('type');        

        if($type == 'product')
        {
            $get_nameIn = Product::pluck('name', 'id')->toArray();
        }
        else if($type == 'brand')
        {
            $get_nameIn = Brand::pluck('name', 'id')->toArray();
        }
        else
        {
            $get_nameIn = Category::pluck('name', 'id')->toArray();
        }
        
        $names_list = ['' => 'Select Name'] + $get_nameIn;

        return Form::select('action_id', $names_list, array('id' => 'action_id'));
    }
}

resources/views/admin/notification/create.blade.php
@extends('admin.layout.layout')
@section('start_form')
    <?= Form::open(['route'=>'notifications.store','role'=>'form','class'=>'m-0','files'=>true,'method'=>'POST']) ?>
@stop
@section('top_fixed_content')
    <nav class="navbar navbar-static-top">
        <div class="title">
            <h4></h4>
        </div>        
        <div class="pl-10">
            <button type="submit" name="save_button" value="save_new" class="btn btn-primary btn-sm disabled-btn" title="Save and new">Save & New</button>
            <button type="submit" name="save_button" value="save_exit" class="btn btn-primary btn-sm disabled-btn" title="Save and push">Save & Push </button>
            <a href="<?= route('notifications.index') ?>" class="btn btn-default btn-sm" title="Cancel">Cancel</a>
        </div>
    </nav>
@stop 
@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <div class="form-group @if($errors->has('title')) {{ 'has-error' }} @endif">
                            <label>Title<sup class="text-danger">*</sup></label>
                            <?= Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title','id'=>'title','maxlength'=>100]); ?>
                            <span id="order_price_error" class="help-inline text-danger"><?= $errors->first('title') ?></span>
                        </div>
                    </div> 
                    <div class="col-md-6">
                        <div class="form-group @if($errors->has('description')) {{ 'has-error' }} @endif">
                            <label>Description</label>
                            <?= Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Description','id'=>'description','rows'=>2]); ?>
                            <span id="description_error" class="help-inline text-danger"><?= $errors->first('description') ?>&nbsp;</span>
                        </div>
                    </div>                      
                    <div class="col-md-6">
                        <div class="form-group @if($errors->has('type')) {{ 'has-error' }} @endif">
                            <label>Type <sup class="text-danger">*</sup></label>
                            <?=Form::select('type',['product'=>'Product','category'=>'Category','brand'=>'Brand'],old('type'), ['class' => 'form-control select2_2','id' => 'type','placeholder'=>'Select Type']);?>
                            <span id="category_id_error" class="help-inline text-danger"><?= $errors->first('type') ?></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group @if($errors->has('action_id')) {{ 'has-error' }} @endif">
                            <label>Name<sup class="text-danger">*</sup></label>
                            <?=Form::select('action_id',$notification,old('action_id'), ['class' => 'form-control select2_2','id' => 'action_id','placeholder'=>'Select Name']);?>
                            <div id="name_box"></div>
                            <span id="name_error" class="help-inline text-danger"><?= $errors->first('action_id') ?></span>
                        </div>
                    </div> 
                    <div class="col-md-6">
                        <div class="form-group @if($errors->has('status')) {{ 'has-error' }} @endif">
                            <label>Status <sup class="text-danger">*</sup></label>
                            <?=Form::select('status',['enable'=>'Enable','disable'=>'Disable'],old('status'), ['class' => 'form-control select2_2 status','id' => 'status','placeholder'=>'Select Type']);?>
                            <span id="category_id_error" class="help-inline text-danger"><?= $errors->first('status') ?></span>
                        </div>
                    </div> 
                    <div class="col-md-6">
                        <div class="form-group @if($errors->has('image')) {{ 'has-error' }} @endif">
                            <label>Banner <sup class="text-danger">*</sup></label>
                            <div class="inputfile-box" id="image_error_div">
                                <input class="inputfile image" id="file" type="file" name="image">
                                <label for="file"><span class="file-box" id="file-name"></span><span class="file-button">Upload</span></label>
                                <span id="image_error" class="help-inline text-danger"><?= $errors->first('image') ?></span>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>    
    <div class="text-right">
        <button type="submit" name="save_button" value="save_new" class="btn btn-primary btn-sm disabled-btn" title="Save and new">Save & New</button>
            <button type="submit" name="save_button" value="save_exit" class="btn btn-primary btn-sm disabled-btn" title="Save and push">Save & Push </button>
            <a href="<?= route('notifications.index') ?>" class="btn btn-default btn-sm" title="Cancel">Cancel</a>
    </div>
@stop
@section('end_form')
    <?= Form::close() ?>
@stop

@section('script')
    <?= Html::script('backend/js/jquery.form.min.js') ?> 
    <?= Html::script('backend/js/select2.min.js') ?> 

    <script type="text/javascript">
        $('#file').change(function(){
            $('#file-name').text($(this)[0].files[0].name);
        });
    </script>
    

    <script type="text/javascript">
        var tag1 = $('#type').select2({
            placeholder : "Select Type"
    
        });
        var tag2 = $('#action_id').select2({
            placeholder : "Select Name"
    
        });
        var tag3 = $('#status').select2({
            placeholder : "Select Status"
    
        });
    </script>   

    <!-- TYPEWISE Name -->
    <script type="text/javascript">
        $(document).ready(function(){

            $("#type").on('change',function() {
               loadName($(this).val());
            });

            function loadName(val)
            {
                var token = "{{csrf_token()}}";
                $.ajax({
                    url        : "<?=URL::route('get.name.notification')?>",
                    type       : 'post',
                    data       : { "type": val , '_token' : token },
                    dataType   : 'html',
                    success    : function(names_list) {
                        var options = $(names_list).html();
                        //console.log($names_list);
                        $('#action_id').val('').trigger('change');
                        $("#action_id").html(options).val({{ old('action_id') }});
                    }
                });
            }
        });
    </script>

    <!-- SCRIPT FOR SELECT TAG-->
    <!-- <script type="text/javascript">
        var tag = $('#type').select2({
            placeholder : "Select Type"    
        });
    </script> -->
    @include('admin.layout.alert')
@stop

resources/views/admin/notification/index.blade.php
 @extends('admin.layout.layout')
@section('top_fixed_content')
<nav class="navbar navbar-static-top">
    <div class="title">
        <h4><i class="fa fa-list"></i>Notification Master</h4>
    </div>
    <div class="top_filter"></div>
    <div class="pl-10">
        <a href="<?= route('notifications.create') ?>" class="btn btn-primary btn-sm" title="Add New">Add New</a>
    </div>
</nav>
@stop
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body table-responsive">
                <div class="text-right">
                    <div class="number-delete">
                        <ul>
                            <li>
                                <p class="mb-0"><span class="num_item"></span>Item Selected.</p>
                            </li>
                            <li class="bulk-dropdown">
                                <a href="javascript:;">Bulk actions<span class="caret"></span></a>
                                <div class="bulk-box">
                                    <div class="bulk-tooltip"></div>
                                    <ul class="bulk-list">
                                        <li><a href="javascript:void(0);" id="delete" class="delete-btn">Delete selected record</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                 <div class="p-20">
                    <table id="supplier_table" class="table table-hover">
                        <thead>
                            <tr>
                                <th class="select-all no-sort">
                                    <div class="animated-checkbox">
                                        <label class="m-0">
                                            <input type="checkbox" id="checkAll" />
                                            <span class="label-text"></span>
                                        </label>
                                    </div>
                                </th>
                                <th>Id</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Type</th>
                                <th>Banner</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            @include('admin.layout.overlay')
        </div>
    </div>
</div>
@stop
<!-- for error list show in model -->
@section('script')

<?=Html::script('backend/plugins/datatable/jquery.dataTables.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/datatable/dataTables.bootstrap.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/sweetalert/sweetalert.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/fnstandrow.js', [], IS_SECURE)?>
<?=Html::script('backend/js/delete_script.js', [], IS_SECURE)?>

<script type="text/javascript">
var table = "supplier_table";
var title = "Are you sure to delete this Notification?";
var text = "You will not be able to recover this record";
var type = "warning";
var delete_path = "<?= route('notifications.delete') ?>";
var token = "<?=csrf_token()?>";

$(function(){
    $('#delete').click(function(){
        var delete_id = $('#'+table+' tbody .checkbox:checked');
        checkLength(delete_id);
    });

    $('#supplier_table').DataTable({
        "bProcessing": false,
        "bServerSide": true,
        "autoWidth": false,
        lengthMenu: [
                [ 10, 25, 50, 100,200,500],
                [ '10', '25', '50','100','200','500']
            ],
        "sAjaxSource": "<?= route('notifications.index')?>",
        "aaSorting": [ 1,"desc"],
        "aoColumns": [
            {   
                mData: "id",
                bSortable:false,
                sWidth:"2%",
                sClass:"text-center",
                mRender: function (v, t, o) {
                    return '<div class="animated-checkbox"><label class="m-0"><input class="checkbox" type="checkbox" id="chk_'+v+'" name="special_id['+v+']" value="'+v+'"/><span class="label-text"></span></label></div>';
                },
            },
            {   mData:"id",sWidth:"16%",bSortable : true,

            mRender : function(v,t,o){  

                var edit_path = "<?= route('notifications.edit',['id'=>':id']) ?>";
                edit_path = edit_path.replace(':id',o['id']);

                var act_html  = '<a title="Edit '+o['id']+'" href="'+edit_path+'">'+ v +'</a>'

                return act_html;
            }
        },
        {   mData:"title",sWidth:"20%",bSortable : true},
        {   mData:"description",sWidth:"20%",bSortable : true},
        {   mData:"type",sWidth:"10%",bSortable : true},
        { "mData": "image",sWidth: "20%",bSortable: false,sClass:'text-center',

            mRender: function(v,t,o){
                //console.log(v);
                if (o['image']) {
                    var act_html = '<img src="' +v+ '" alt="' +o[1]+ '" style="border:1px solid #000;width:101px;" />';
                    console.log(act_html);
                }else{
                    var act_html = 'No Image';
                }
                return act_html;
            }
        },
        {   mData:"status",sWidth:"20%",bSortable : false,
        mRender: function(v,t,o){
                    if (v == 'enable') {
                        var act_html = '<span class="badge badge-success">Enable</span>';
                    }else{
                        var act_html = '<span class="badge badge-danger">Disable</span>';
                    }
                    return act_html;}},
        ],
        fnPreDrawCallback : function() { $("div.overlay").css('display','flex'); },
        fnDrawCallback : function (oSettings) {
            $("div.overlay").hide();
        },
    });
});
</script>
@include('admin.layout.alert')
@stop