routes/admin.php
<?php


Route::group(array('namespace'=>'Admin','prefix' => 'admin'), function () {

	Route::get('/admin', function(){
		return redirect()->route('admin.login.get');
	});

	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

	Route::get('reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

	Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.reset');

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

	Route::post('/login-post', 'Auth\AdminLoginController@login')->name('admin.login.post');

	Route::group(['middleware' => ['admin']], function () {

		//route for dashboard
		Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
		//route for logout
		Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
		//route for change-password
	});

});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login.get');
});

// Route::get('admin/change-password',function(){
// 	return view('admin.changepassword');
// });
Route::get('admin/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\AdminLoginController@login')->name('admin.login');

Route::post('admin/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');
Route::get('admin/password/reset/{token?}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get('admin/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout');

Route::post('admin/password/reset-password', 'Admin\Auth\ResetPasswordController@reset')->name('password.reset.post.password');

Route::get('/products/export','Admin\ProductController@exceltoexport')->name('products.export');
Route::post('notifications/names','Admin\NotificationController@getName')->name('get.name.notification');
Route::post('banners/names','Admin\BannerController@getName')->name('get.name.banner');
Route::get('admin/category/categoryorder','Admin\CategoryController@CategoryOrder')->name('category.order.get');
Route::get('admin/brand/brandorder','Admin\BrandController@BrandOrder')->name('brand.order.get');
Route::get('admin/banner/bannerorder','Admin\BannerController@BannerOrder')->name('banner.order.get');
Route::get('admin/products/suggetion','Admin\ProductController@CollectionSuggetion')->name('products.collection.suggetion');
Route::get('admin/product/suggetion/{id}','Admin\ProductController@CollectionSuggetionEdit')->name('products.suggetion.update');

Route::get('dealer/reset','Admin\UserController@ResetApiViewFile')->name('dealer.reset');
Route::post('api/reset/password','Admin\UserController@ApiResetPassword')->name('dealer.reset.password');

Route::group(['namespace'=>'Admin','prefix'=>'admin','middleware'=>'admin'],function(){
Route::post('dealers/deactive/{id}','UserController@deActive')->name('dealers.deactive');
	Route::resource('/brands','BrandController');
	Route::post('brands/delete','BrandController@delete')->name('brands.delete');
	Route::post('brand/order','BrandController@Order')->name('brand.order');	

	Route::resource('/category','CategoryController');
	Route::post('category/delete','CategoryController@delete')->name('category.delete');
	Route::post('category/order','CategoryController@Order')->name('category.order');

	Route::resource('/products','ProductController',['except'=>'update']);
	Route::post('/products/delete','ProductController@delete')->name('products.delete');
	Route::post('/products/update/{id}','ProductController@update')->name('products.update');
	Route::post('/products/category','ProductController@getCategory')->name('products.getcategory');
	Route::post('/products/image','ProductController@deleteImage')->name('delete.image');
	Route::post('/products/multipleimage','ProductController@UploadImage')->name('upload.url');
	Route::post('/products/size','ProductController@getSize')->name('products.getsize');	

	Route::post('/orders/{id}','OrderController@update')->name('orders.update');
	Route::post('/orders/store/invoice','OrderController@invoiceStore')->name('orders.store.invoice');
	Route::get('/orders/cancel','OrderController@OrderCancel')->name('orders.cancel');

	Route::resource('/orders','OrderController',['except'=>'update']);
	Route::post('/orders/delete','OrderController@delete')->name('orders.delete');
	Route::post('/orders/store/city','OrderController@getCity')->name('orders.getcity');
	Route::post('/orders/store/shippingcity','OrderController@getShippingCity')->name('orders.shippingcity');
	Route::post('/orders/store/getproductdata', 'OrderController@getProductData')->name('orders.getproductdata');
	Route::post('/orders/store/getdealerdata', 'OrderController@getDealerData')->name('orders.getdealerdata');
	Route::post('/orders/store/size','OrderController@getSize')->name('orders.getsize');

	Route::post('/user-plan/store','UserPlanController@store')->name('user-plan.store');
	Route::post('/user-plan/update/{id}','UserPlanController@update')->name('user-plan.update');
	Route::resource('/user-plan','UserPlanController',['except'=>'store','update']);
	Route::post('/user-plan/delete','UserPlanController@delete')->name('user-plan.delete');
	Route::post('/user-plan/category','UserPlanController@getCategory')->name('user-plan.getcategory');
	Route::post('/user-plan/product','UserPlanController@getProduct')->name('user-plan.getproduct');

	Route::resource('/coupons','CoupanCodeController');
	Route::post('/coupons/delete','CoupanCodeController@delete')->name('coupons.delete');
	// Route::post('/coupans/category','CoupanCode@getCategory')->name('coupans.getcategory');

	Route::resource('/color','ColorController');
	Route::post('color/delete','ColorController@delete')->name('color.delete');

	Route::resource('/size','SizeController');
	Route::post('size/delete','SizeController@delete')->name('size.delete');

	Route::resource('/pages','StaticPageController');
	Route::post('pages/delete','StaticPageController@delete')->name('pages.delete');


	Route::resource('/shipment','ShipmentController');
	Route::post('shipment/delete','ShipmentController@delete')->name('shipment.delete');

	Route::resource('/notifications','NotificationController');
	Route::post('notifications/delete','NotificationController@delete')->name('notifications.delete');

	Route::resource('/banners','BannerController');
	Route::post('banner/order','BannerController@Order')->name('banner.order');	
	Route::post('banners/delete','BannerController@delete')->name('banners.delete');
	

	Route::get('/dealers/view/{id}','UserController@view')->name('dealers.view');
	Route::resource('/dealers','UserController',['except'=>'show']);

	Route::get('/pdf','PdfController@downloadpdf')->name('pdf.get');

	Route::resource('/sales-person','SalesPersonController');
	Route::post('/sales-person/delete','SalesPersonController@delete')->name('sales-person.delete');
	Route::resource('/reports','ReportController');

	Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth:admin']], function () {

			Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
			Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
	});
});

app/Models/SalesPerson.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SalesPerson extends Model
{
	protected $table = 'sales_persons';
    protected $fillable = ['id','fullname','username','password','status'];
}

app/Http/Controllers/Admin/SalesPersonController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\SalesPerson;
use App\Http\Requests\SalesPersonRequest;
use App\Events\SalesPersonEvent;
use Event;
use App\Models\User;
use DB;

class SalesPersonController extends Controller
{
	public function index(Request $request) {
		if($request->ajax()){
            $where_str    = "1 = ?";
            $where_params = array(1); 

            if (!empty($request->input('sSearch')))
            {
                $search     = $request->input('sSearch');
                $where_str .= " and (firstname like \"%{$search}%\""
                . " or lastname like \"%{$search}%\""
                . " or email like \"%{$search}%\""
                . ")";
            }                                            

            $columns = ['updated_at','firstname', 'lastname','email'];

            $sales_person_columns_count = User::select($columns)
                              ->where('type','=','seller')
									            ->whereRaw($where_str, $where_params)
									            ->count();

            $sales_person_list = User::select($columns)
                            ->where('type','=','seller')
           									->whereRaw($where_str, $where_params);

            if($request->get('iDisplayStart') != '' && $request->get('iDisplayLength') != ''){
                $sales_person_list = $sales_person_list->take($request->input('iDisplayLength'))
                ->skip($request->input('iDisplayStart'));
            }          

            if($request->input('iSortCol_0')){
                $sql_order='';
                for ( $i = 0; $i < $request->input('iSortingCols'); $i++ )
                {
                    $column = $columns[$request->input('iSortCol_' . $i)];
                    if(false !== ($index = strpos($column, ' as '))){
                        $column = substr($column, 0, $index);
                    }
                    $sales_person_list = $sales_person_list->orderBy($column,$request->input('sSortDir_'.$i));   
                }
            } 


            $sales_person_list = $sales_person_list->get();

            $response['iTotalDisplayRecords'] = $sales_person_columns_count;
            $response['iTotalRecords'] = $sales_person_columns_count;
            $response['sEcho'] = intval($request->input('sEcho'));
            $response['aaData'] = $sales_person_list->toArray();

            return $response;
        }
    	return view('admin.sales_person.index');
	}

	public function create() {
	  	return view('admin.sales_person.create');
	}

	public function store(SalesPersonRequest $request) {

	   	$sales_person_data = $request->all();
       
       $sales_person_data['firstname'] = strip_tags($request->firstname);        
        $sales_person_data['lastname'] = strip_tags($request->lastname);
        Event::fire(new SalesPersonEvent($sales_person_data));
        
        if($request->save_button == 'save_new') 
        {
            return back()->with('message','Record added  Successfully')
            ->with('message_type','success');
        }
        return redirect()->route('sales-person.index')->with('message','Record added Successfully')->with('message_type','success');
	}

	public function edit($id) {
		// $sales_person_data = SalesPerson::find($id);
		// $id = $sales_person_data['id'];

	 // 	return view('admin.sales_person.edit',compact('sales_person_data','id'));
	}

	public function update(SalesPersonRequest $request,$id) {
		// $sales_person_data = $request->all();

  //      	$sales_person_data['id'] = $id;

  //       Event::fire(new SalesPersonEvent($sales_person_data));
        
  //       if($request->save_button == 'save_new') 
  //       {
  //           return back()->with('message','Record updated  Successfully')
  //           ->with('message_type','success');
  //       }
  //       return redirect()->route('sales-person.index')->with('message','Record updated Successfully')->with('message_type','success');
	}

	public function delete(Request $request) {
		
	 // 	$id = $request->get('id');
	     
		// if (!is_array($id)) {
		// 	$id = array($id);
		// }
	    
	 //    $sales_person_delete = SalesPerson::whereIn('id',$id)->delete();

	 //    return response()->json(array('success' => true), 200);
	}
}

resources/views/admin/sales_person/create.blade.php
@extends('admin.layout.layout')
@section('start_form')
    <?=Form::open(['route'=>'sales-person.store','role'=>'form','method' => 'POST', 'class' => 'm-0 form-horizontal', 'id'=>'status_form_data'])?>
@stop
@section('top_fixed_content')
<nav class="navbar navbar-static-top">
    <div class="title">
        <h4></h4>
    </div>
    <div class="pl-10">
        <button type="submit" name="save_button" value="save_new" class="btn btn-primary btn-sm disabled-btn" title="Save and new">Save & New</button>
        <button type="submit" name="save_button" value="save_exit" class="btn btn-primary btn-sm disabled-btn" title="Save and exit">Save & exit </button>
        <a href="<?= route('sales-person.index') ?>" class="btn btn-default btn-sm" title="Cancel">Cancel</a>
    </div>
</nav>
@stop
@section('content')
    <input type="hidden" name="id" id="id" value="">
    <div class="row">
    <div class="card col-md-12 mb-30">
        <div class="bg-white p-5 row m-0 box-shadow">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="form-group row">
                        <label class="control-label col-md-3">FirstName<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('firstname')) {{ 'has-error' }} @endif">
                            <?= Form::text('firstname',old('firstname'),['class' => 'form-control char_only','placeholder'=>'First Name','id'=>'firstname']); ?>
                            <span id="firstname_error" class="help-inline text-danger error_msg"><?= $errors->first('firstname') ?></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-3">LastName<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('lastname')) {{ 'has-error' }} @endif">
                            <?= Form::text('lastname',old('lastname'),['class' => 'form-control char_only','placeholder'=>'Last Name','id'=>'lastname']); ?>
                            <span id="lastname_error" class="help-inline text-danger error_msg"><?= $errors->first('lastname') ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                 <div class="form-group">
                    <div class="form-group row">
                        <label class="control-label col-md-3">Email<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('email')) {{ 'has-error' }} @endif">
                            <?= Form::text('email',old('email'),['class' => 'form-control','placeholder'=>'Email','id'=>'email']); ?>
                            <span id="email_error" class="help-inline text-danger error_msg"><?= $errors->first('email') ?></span>
                        </div>
                    </div><div class="form-group row">
                        <label class="control-label col-md-3">Password<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('password')) {{ 'has-error' }} @endif">
                            <?= Form::password('password',['class' => 'form-control mb-0','placeholder'=>'Password','id'=>'password']); ?>
                            <span id="password_error" class="help-inline text-danger error_msg"><?= $errors->first('password') ?></span>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>  
</div>
<div class="text-right">
    <button type="submit" name="save_button" value="save_new" class="btn btn-primary btn-sm disabled-btn" title="Save and new">Save & New</button>
    <button type="submit" name="save_button" value="save_exit" class="btn btn-primary btn-sm disabled-btn" title="Save and exit">Save & exit </button>
    <a href="<?= route('sales-person.index') ?>" class="btn btn-default btn-sm" title="Cancel">Cancel</a>
</div>
@stop
<?=Form::close()?>

@section('script')
    <script type="text/javascript">
        $(".char_only").keypress(function (e) {
             if (e.which != 8 && e.which != 0 && e.which != 32 && (e.which < 97 || e.which > 122)&& (e.which < 65 || e.which > 90))return !1           
           });
    </script>
@stop

resources/views/admin/sales_person/edit.blade.php
@extends('admin.layout.layout')
@section('start_form')
    <?=Form::model($sales_person_data,['route'=>['sales-person.update',$id],'role'=>'form','method' => 'PATCH', 'class' => 'm-0 form-horizontal', 'id'=>'status_form_data'])?>
@stop
@section('top_fixed_content')
<nav class="navbar navbar-static-top">
    <div class="title">
        <h4></h4>
    </div>
    <div class="pl-10">
        <button type="submit" name="save_button" value="save_new" class="btn btn-primary btn-sm disabled-btn" title="Save and new">Save & New</button>
        <button type="submit" name="save_button" value="save_exit" class="btn btn-primary btn-sm disabled-btn" title="Save and exit">Save & exit </button>
        <a href="<?= route('sales-person.index') ?>" class="btn btn-default btn-sm" title="Cancel">Cancel</a>
    </div>
</nav>
@stop
@section('content')
    <input type="hidden" name="id" id="id" value="">
@include('admin.sales_person.form')
<div class="text-right">
    <button type="submit" name="save_button" value="save_new" class="btn btn-primary btn-sm disabled-btn" title="Save and new">Save & New</button>
    <button type="submit" name="save_button" value="save_exit" class="btn btn-primary btn-sm disabled-btn" title="Save and exit">Save & exit </button>
    <a href="<?= route('sales-person.index') ?>" class="btn btn-default btn-sm" title="Cancel">Cancel</a>
</div>
@stop
<?=Form::close()?>

resources/views/admin/sales_person/form.blade.php
<div class="row">
    <div class="card col-md-12 mb-30">
        <div class="bg-white p-5 row m-0 box-shadow">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="form-group row">
                        <label class="control-label col-md-3">FirstName<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('firstname')) {{ 'has-error' }} @endif">
                            <?= Form::text('firstname',old('firstname'),['class' => 'form-control','placeholder'=>'First Name','id'=>'firstname']); ?>
                            <span id="firstname_error" class="help-inline text-danger error_msg"><?= $errors->first('firstname') ?></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-3">LastName<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('lastname')) {{ 'has-error' }} @endif">
                            <?= Form::text('lastname',old('lastname'),['class' => 'form-control','placeholder'=>'Last Name','id'=>'lastname']); ?>
                            <span id="lastname_error" class="help-inline text-danger error_msg"><?= $errors->first('lastname') ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                 <div class="form-group">
                    <div class="form-group row">
                        <label class="control-label col-md-3">Email<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('email')) {{ 'has-error' }} @endif">
                            <?= Form::text('email',old('email'),['class' => 'form-control','placeholder'=>'Email','id'=>'email']); ?>
                            <span id="email_error" class="help-inline text-danger error_msg"><?= $errors->first('email') ?></span>
                        </div>
                    </div>
                    @if(Request::segment(1) == 'admin' && Request::segment(3) == 'create')
                    <div class="form-group row">
                        <label class="control-label col-md-3">Password<sup class="text-danger">*</sup></label>
                        <div class="col-md-9 @if($errors->has('password')) {{ 'has-error' }} @endif">
                            <?= Form::password('password',['class' => 'form-control mb-0','placeholder'=>'Password','id'=>'password']); ?>
                            <span id="password_error" class="help-inline text-danger error_msg"><?= $errors->first('password') ?></span>
                        </div>
                    </div> 
                </div>
                @endif
            </div>
        </div>
    </div>
   
</div>

resources/views/admin/sales_person/index.blade.php
@extends('admin.layout.layout')
@section('top_fixed_content')
<nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
    <div class="title">
        <h4><i class="fa fa-list"></i>Sales Person</h4>
    </div>
    <div class="pl-10">
        <a href="<?=route('sales-person.create')?>" class="btn btn-primary btn-sm" title="Add New"> Add New</a>
    </div>
</nav>
@stop
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body table-responsive">
                <table id="salesperson_table" class="table table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>FirstName</th>
                            <th>LastName</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            @include('admin.layout.overlay')
        </div>
    </div>
</div>
@stop
<!-- for error list show in model -->
@section('script')

<?=Html::script('backend/plugins/datatable/jquery.dataTables.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/datatable/dataTables.bootstrap.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/sweetalert/sweetalert.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/fnstandrow.js', [], IS_SECURE)?>
<?=Html::script('backend/js/delete_script.js', [], IS_SECURE)?>

<script type="text/javascript">

$(function(){
    $('#salesperson_table').DataTable({
        "bProcessing": false,
        "bServerSide": true,
        "autoWidth": true,
        lengthMenu: [
                [ 10, 25, 50, 100,200,500],
                [ '10', '25', '50','100','200','500']
            ],
        "sAjaxSource": "<?= route('sales-person.index')?>",
        "aaSorting": [ 0,"desc"],
        "aoColumns": [
            { mData:"updated_at",bSortable : false,sClass : 'text-center',sWidth:"16%",bVisible : false},
            { mData:"firstname",sWidth:"30%",bSortable : true},
            { mData:"lastname",sWidth:"20%",bSortable : true},
            { mData:"email",bSortable : true ,sWidth:"30%"},
        ],
        fnPreDrawCallback : function() { $("div.overlay").css('display','flex'); },
        fnDrawCallback : function (oSettings) {
            $("div.overlay").hide();
        },
    });
});
</script>
@include('admin.layout.alert')
@stop