routes/admin.php
<?php


Route::group(array('namespace'=>'Admin','prefix' => 'admin'), function () {

	Route::get('/admin', function(){
		return redirect()->route('admin.login.get');
	});

	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

	Route::get('reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

	Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.reset');

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

	Route::post('/login-post', 'Auth\AdminLoginController@login')->name('admin.login.post');

	Route::group(['middleware' => ['admin']], function () {

		//route for dashboard
		Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
		//route for logout
		Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
		//route for change-password
	});

});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login.get');
});

// Route::get('admin/change-password',function(){
// 	return view('admin.changepassword');
// });
Route::get('admin/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\AdminLoginController@login')->name('admin.login');

Route::post('admin/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');
Route::get('admin/password/reset/{token?}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get('admin/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout');

Route::post('admin/password/reset-password', 'Admin\Auth\ResetPasswordController@reset')->name('password.reset.post.password');

Route::get('/products/export','Admin\ProductController@exceltoexport')->name('products.export');
Route::post('notifications/names','Admin\NotificationController@getName')->name('get.name.notification');
Route::post('banners/names','Admin\BannerController@getName')->name('get.name.banner');
Route::get('admin/category/categoryorder','Admin\CategoryController@CategoryOrder')->name('category.order.get');
Route::get('admin/brand/brandorder','Admin\BrandController@BrandOrder')->name('brand.order.get');
Route::get('admin/banner/bannerorder','Admin\BannerController@BannerOrder')->name('banner.order.get');
Route::get('admin/products/suggetion','Admin\ProductController@CollectionSuggetion')->name('products.collection.suggetion');
Route::get('admin/product/suggetion/{id}','Admin\ProductController@CollectionSuggetionEdit')->name('products.suggetion.update');

Route::get('dealer/reset','Admin\UserController@ResetApiViewFile')->name('dealer.reset');
Route::post('api/reset/password','Admin\UserController@ApiResetPassword')->name('dealer.reset.password');

Route::group(['namespace'=>'Admin','prefix'=>'admin','middleware'=>'admin'],function(){
Route::post('dealers/deactive/{id}','UserController@deActive')->name('dealers.deactive');
	Route::resource('/brands','BrandController');
	Route::post('brands/delete','BrandController@delete')->name('brands.delete');
	Route::post('brand/order','BrandController@Order')->name('brand.order');	

	Route::resource('/category','CategoryController');
	Route::post('category/delete','CategoryController@delete')->name('category.delete');
	Route::post('category/order','CategoryController@Order')->name('category.order');

	Route::resource('/products','ProductController',['except'=>'update']);
	Route::post('/products/delete','ProductController@delete')->name('products.delete');
	Route::post('/products/update/{id}','ProductController@update')->name('products.update');
	Route::post('/products/category','ProductController@getCategory')->name('products.getcategory');
	Route::post('/products/image','ProductController@deleteImage')->name('delete.image');
	Route::post('/products/multipleimage','ProductController@UploadImage')->name('upload.url');
	Route::post('/products/size','ProductController@getSize')->name('products.getsize');	

	Route::post('/orders/{id}','OrderController@update')->name('orders.update');
	Route::post('/orders/store/invoice','OrderController@invoiceStore')->name('orders.store.invoice');
	Route::get('/orders/cancel','OrderController@OrderCancel')->name('orders.cancel');

	Route::resource('/orders','OrderController',['except'=>'update']);
	Route::post('/orders/delete','OrderController@delete')->name('orders.delete');
	Route::post('/orders/store/city','OrderController@getCity')->name('orders.getcity');
	Route::post('/orders/store/shippingcity','OrderController@getShippingCity')->name('orders.shippingcity');
	Route::post('/orders/store/getproductdata', 'OrderController@getProductData')->name('orders.getproductdata');
	Route::post('/orders/store/getdealerdata', 'OrderController@getDealerData')->name('orders.getdealerdata');
	Route::post('/orders/store/size','OrderController@getSize')->name('orders.getsize');

	Route::post('/user-plan/store','UserPlanController@store')->name('user-plan.store');
	Route::post('/user-plan/update/{id}','UserPlanController@update')->name('user-plan.update');
	Route::resource('/user-plan','UserPlanController',['except'=>'store','update']);
	Route::post('/user-plan/delete','UserPlanController@delete')->name('user-plan.delete');
	Route::post('/user-plan/category','UserPlanController@getCategory')->name('user-plan.getcategory');
	Route::post('/user-plan/product','UserPlanController@getProduct')->name('user-plan.getproduct');

	Route::resource('/coupons','CoupanCodeController');
	Route::post('/coupons/delete','CoupanCodeController@delete')->name('coupons.delete');
	// Route::post('/coupans/category','CoupanCode@getCategory')->name('coupans.getcategory');

	Route::resource('/color','ColorController');
	Route::post('color/delete','ColorController@delete')->name('color.delete');

	Route::resource('/size','SizeController');
	Route::post('size/delete','SizeController@delete')->name('size.delete');

	Route::resource('/pages','StaticPageController');
	Route::post('pages/delete','StaticPageController@delete')->name('pages.delete');


	Route::resource('/shipment','ShipmentController');
	Route::post('shipment/delete','ShipmentController@delete')->name('shipment.delete');

	Route::resource('/notifications','NotificationController');
	Route::post('notifications/delete','NotificationController@delete')->name('notifications.delete');

	Route::resource('/banners','BannerController');
	Route::post('banner/order','BannerController@Order')->name('banner.order');	
	Route::post('banners/delete','BannerController@delete')->name('banners.delete');
	

	Route::get('/dealers/view/{id}','UserController@view')->name('dealers.view');
	Route::resource('/dealers','UserController',['except'=>'show']);

	Route::get('/pdf','PdfController@downloadpdf')->name('pdf.get');

	Route::resource('/sales-person','SalesPersonController');
	Route::post('/sales-person/delete','SalesPersonController@delete')->name('sales-person.delete');
	Route::resource('/reports','ReportController');

	Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth:admin']], function () {

			Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
			Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
	});
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\PlanProductDetail;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Color;
use App\Models\BrandSize;
use App\Models\ProductSize;
use App\Models\UserPlan;
use App\Models\ProductVariant;
use App\Http\Requests\ProductRequest;
use Event;
use Form,Excel;
use App\Events\ProductEvent;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            $where_str    = "1 = ?";
            $where_params = array(1); 

            if (!empty($request->input('sSearch')))
            {
                $search     = $request->input('sSearch');
                $where_str .= " and (products.name like \"%{$search}%\""
                . " or products.sku like \"%{$search}%\""
                . " or brands.name like \"%{$search}%\""
                . " or categories.name like \"%{$search}%\""
                . " or products.original_price like \"%{$search}%\""
                . " or products.tax like \"%{$search}%\""
                . ")";
            }  

            if($request->has('todate') && ($request->has('fromdate'))){
                $todate = $request->get('todate');
                $fromdate = $request->get('fromdate');
                $where_str .= " and (DATE(products.created_at) >= '$fromdate')";
                $where_str .= " and (DATE(products.created_at) <= '$todate')";
            }                                          

            $columns = ['products.created_at','products.id','products.name','products.sku','categories.name as category','brands.name as brand','products.original_price','products.tax'];

            $companymaster_columns_count = Product::select($columns)
            ->leftjoin('brands','brands.id','=','products.brand_id')
            ->leftjoin('categories','categories.id','=','products.category_id')
            ->whereRaw($where_str, $where_params)
            ->count();

            $companymaster_list = Product::select($columns)
            ->leftjoin('brands','brands.id','=','products.brand_id')
            ->leftjoin('categories','categories.id','=','products.category_id')
            ->whereRaw($where_str, $where_params);

            if($request->get('iDisplayStart') != '' && $request->get('iDisplayLength') != ''){
                $companymaster_list = $companymaster_list->take($request->input('iDisplayLength'))
                ->skip($request->input('iDisplayStart'));
            }          

            if($request->input('iSortCol_0')){
                $sql_order='';
                for ( $i = 0; $i < $request->input('iSortingCols'); $i++ )
                {
                    $column = $columns[$request->input('iSortCol_' . $i)];
                    if(false !== ($index = strpos($column, ' as '))){
                        $column = substr($column, 0, $index);
                    }
                    $companymaster_list = $companymaster_list->orderBy($column,$request->input('sSortDir_'.$i));   
                }
            } 


            $companymaster_list = $companymaster_list->get();

            $response['iTotalDisplayRecords'] = $companymaster_columns_count;
            $response['iTotalRecords'] = $companymaster_columns_count;
            $response['sEcho'] = intval($request->input('sEcho'));
            $response['aaData'] = $companymaster_list->toArray();

            return $response;
        }
        return view('admin.product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $brand = Brand::orderBy('name','asc')->pluck('name','id')->toArray();
        $color = Color::orderBy('name','asc')->pluck('name','id')->toArray();
        $user_plans = UserPlan::pluck('user_plan', 'id')->toArray();
        $user_flag=[];
        if(!empty($user_plans))
        {
            $user_flag = 1;
        }
        else
        {
          $user_flag = 0;  
        }

        $category = (old('brand_id')) ? [""=>"Select Category"] + Category::where("brand_id",old('brand_id'))->orderBy('name','asc')->pluck('name', 'id')->toArray() : array(""=>"Select Category");

        return view('admin.product.create',compact('brand','category','color','user_plans','user_flag'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $product_data = $request->all();
        //print_r($product_data);

        $product_data['name'] = strip_tags($request->name);        
        $product_data['sku'] = strip_tags($request->sku);
        Event::fire(new ProductEvent($product_data));
        
        if($request->save_button == 'save_new') 
        {
            return back()->with('message','Record added  Successfully')
            ->with('message_type','success');
        }
        return redirect()->route('products.index')->with('message','Record added Successfully')->with('message_type','success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product_data = Product::find($id);
        $id = $product_data['id'];

        $product_detail = json_decode($product_data['attribute'],true);
        $information_detail = json_decode($product_data['information'],true);
        $product_key_value = [];

        foreach ($product_detail as $key => $single_product_data) {

            foreach ($single_product_data as $single_key => $single_value) {

                $product_single['product_key'] = $single_value['product_key'];
                $product_single['product_value'] = $single_value['product_value'];


                $product_key_value[] = $product_single;
            }

        }

        $information_key_value = [];

        foreach ($information_detail as $key => $single_information_data) {

            foreach ($single_information_data as $single_key => $single_value) {

                $information_single['information_key'] = $single_value['information_key'];
                $information_single['information_value'] = $single_value['information_value'];


                $information_key_value[] = $information_single;
            }

        }
        $product_variant_detail = ProductSize::select('product_sizes.qty','product_variants.color_id','product_sizes.size_id','sizes.name as name')
        ->leftjoin('product_variants','product_variants.id','=','product_sizes.product_variant_id')
        ->leftjoin('sizes','sizes.id','=','product_sizes.size_id')->where('product_variants.product_id',$id)->get()->toArray();
        
            $array = array_unique(array_column($product_variant_detail, 'color_id'));
            $unique_data = array_intersect_key($product_variant_detail, $array);

        $colorArry   = [];
       
        foreach ($product_variant_detail as $key => $value) {

            if(array_key_exists($value['color_id'], $colorArry))
            {
                $colorArry[$value['color_id']][$value['name']] = $value['qty'];
            }
            else
            {
                $colorArry[$value['color_id']][$value['name']] = $value['qty'];
            }
        }
         
        $colorArr = [];
        foreach($colorArry as $key => $value)
        {
            foreach ($value as $subKey => $subValue) {
                $colorArr[$key][$subKey] = $subValue;
                $colorArr[$key]['color_id'] = $key;
            }
        }

        $final_product_variant_arr = array_values($colorArr);
        
        $brand = Brand::orderBy('name','asc')->pluck('name','id')->toArray();
        $color = Color::orderBy('name','asc')->pluck('name','id')->toArray();

        $gallary_images = ProductImage::where('product_id', $id)->get()->toArray();
        
        foreach ($gallary_images as $key => $single_image) {

            $img_name = explode('/',$single_image['image'])[5];
            $image[$key]['caption'] = $img_name;
            $image[$key]['name'] = $single_image['image'];
            $image[$key]['key'] = $single_image['id'];
            $image[$key]['url'] = route('delete.image');
            $image[$key]['extra']['_token'] = csrf_token();
            $image[$key]['extra']['image_name'] = $img_name;
        }
        $multi_images = json_encode($image);
        $image_data = '';
        if(!empty($image))
        {
            $image_data = stripcslashes(json_encode($image));
        }
        
        $image = json_decode($image_data,true);
        $images = [];
        foreach ($image as $key => $value) {
            $images[] = $value['name'];
        }
        $images = json_encode($images);
        
        $user_plans = UserPlan::pluck('user_plan', 'id')->toArray();
        $user_flag=[];
        if(!empty($user_plans))
        {
            $user_flag = 1;
        }
        else
        {
          $user_flag = 0;  
        }
        $product_details = PlanProductDetail::select('user_plan_id')->where('product_id',$id)->get()->toArray();
        $old_plan = [];
        foreach ($product_details as $key => $value) {
            $old_plan[$value['user_plan_id']] = $value['user_plan_id'];
        }

resources/views/admin/product/index.blade.php
@extends('admin.layout.layout')
@section('top_fixed_content')
    <?= Html::style('backend/css/dataranger.css',[],IS_SECURE) ?>
<nav class="navbar navbar-static-top">
    <div class="title">
        <h4><i class="fa fa-list"></i>Product Master</h4>
    </div>
    <div class="top_filter"></div>
    <div class="pl-10">
        <a href="<?= route('products.create') ?>" class="btn btn-primary btn-sm" title="Add New">Add New</a>
    </div>
</nav>

@stop
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body table-responsive">
                <div class="text-right">
                    <div class="number-delete">
                        <ul>
                            <li>
                                <p class="mb-0"><span class="num_item"></span>Item Selected.</p>
                            </li>
                            <li class="bulk-dropdown">
                                <a href="javascript:;">Bulk actions<span class="caret"></span></a>
                                <div class="bulk-box">
                                    <div class="bulk-tooltip"></div>
                                    <ul class="bulk-list">
                                        <li><a href="javascript:void(0);" id="delete" class="delete-btn">Delete selected record</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                 <div class="p-20">
                    <table id="supplier_table" class="table table-hover">
                        <thead>
                            <tr>
                                <th class="select-all no-sort">
                                    <div class="animated-checkbox">
                                        <label class="m-0">
                                            <input type="checkbox" id="checkAll" />
                                            <span class="label-text"></span>
                                        </label>
                                    </div>
                                </th>
                                <th>Name</th>
                                <th>SKU</th>
                                <th>Brand</th>
                                <th>Category</th>
                                <th>Price</th>
                                <th>Tax</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            @include('admin.layout.overlay')
        </div>
    </div>
</div>
@stop
<!-- for error list show in model -->
@section('script')

<?=Html::script('backend/plugins/datatable/jquery.dataTables.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/datatable/dataTables.bootstrap.min.js', [], IS_SECURE)?>
<?= Html::script('backend/js/moment.min.js',[],IS_SECURE) ?>
<?= Html::script('backend/js/dateranger.js',[],IS_SECURE) ?> 
<?=Html::script('backend/plugins/sweetalert/sweetalert.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/fnstandrow.js', [], IS_SECURE)?>
<?=Html::script('backend/js/delete_script.js', [], IS_SECURE)?>

<script type="text/javascript">
    var table = "supplier_table";
    var title = "Are you sure to delete this Product?";
    var text = "You will not be able to recover this record";
    var type = "warning";
    var delete_path = "<?= route('products.delete') ?>";
    var token = "<?=csrf_token()?>";

    $(function(){
        $('#delete').click(function(){
            var delete_id = $('#'+table+' tbody .checkbox:checked');
            checkLength(delete_id);
        });

        $('#supplier_table').DataTable({
            "bProcessing": false,
            "bServerSide": true,
            "autoWidth": false,
            lengthMenu: [
                [ 10, 25, 50, 100,200,500],
                [ '10', '25', '50','100','200','500']
            ],
            "sAjaxSource": "<?= route('products.index')?>",
            "aaSorting": [ 1,"desc"],
            "aoColumns": [
                {   
                    mData: "id",
                    bSortable:false,
                    sWidth:"2%",
                    sClass:"text-center",
                    mRender: function (v, t, o) {
                        return '<div class="animated-checkbox"><label class="m-0"><input class="checkbox" type="checkbox" id="chk_'+v+'" name="special_id['+v+']" value="'+v+'"/><span class="label-text"></span></label></div>';
                    },
                },
                {   mData:"name",sWidth:"16%",bSortable : true,

                mRender : function(v,t,o){  

                    var edit_path = "<?= route('products.edit',['id'=>':id']) ?>";
                    edit_path = edit_path.replace(':id',o['id']);

                    var act_html  = '<a title="Edit '+o['name']+'" href="'+edit_path+'">'+ v +'</a>'

                    return act_html;
                }
            },
            { mData:"sku",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"brand",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"category",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"original_price",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"tax",bSortable : true,sClass : 'text-center',sWidth:"16%"},

            ],
            fnPreDrawCallback : function() { $("div.overlay").css('display','flex'); },
            fnDrawCallback : function (oSettings) {
                $("div.overlay").hide();
            },
        });
    });
</script>    
@include('admin.layout.alert')
@stop

resources/views/admin/product/product_variant.blade.php
 <table class="table m-0 v-top verticle-align">
    <thead>
        <tr>
            <th style="border:none" width="150px">Color <sup class="text-danger">*</sup></th>
            @foreach($data as $key=>$value)
                @if($count == 1)
                	<th class="variant-detail-th" style="border:none">{{$value['name']}}<sup class="text-danger">*</sup></th>
                @else
                    <th style="border:none">{{$value['name']}}<sup class="text-danger">*</sup></th>
                @endif
            @endforeach
            <th style="border:none"></th>
        </tr>
    </thead>
    <tbody>
        <tr id="product">
            <td style="border:none" valign="top">
                <?=Form::select('color_id',$color,old('color_id'), ['class' => 'form-control null_value_class color_id','id' => 'color_id','placeholder'=>'Select Color','style'=>'width:150px']);?>
                <span id="product.product.color_id_error" class="help-inline text-danger"><?= $errors->first('product.product.color_id') ?></span>
            </td>
            @foreach($data as $key=>$value)
                <?php $size = $value['name']?>
	            <td style="border:none" valign="top">
                    @if($count == 1)
                        <?=Form::text($size,old('size'), ['class' => 'form-control number_only null_value_class  '.$size,'id'=>'qty','placeholder'=>'Qty of '. $size.' size']);?>
                    @else
	                   <?=Form::text($size,old('size'), ['class' => 'form-control number_only null_value_class  '.$size,'id'=>'qty','placeholder'=>'Qty of '. $size.' size']);?>
                    @endif
	                <span id="qty_error" class="help-inline text-danger"><?= $errors->first('product.product.qty') ?></span>
	            </td>
            @endforeach
            <td style="border:none" valign="top">
                <a id="product_remove" class="pt-10 pull-left btn-remove"><i class="fa fa-minus-circle fa-small pull-left"></i></a>
                <a id="product_add" class="pt-10 pull-left btn-add" ><i class="fa fa-plus-circle fa-small pull-left" ></i></a>
            </td>
        </tr>
    </tbody>
</table>