routes/admin.php
<?php


Route::group(array('namespace'=>'Admin','prefix' => 'admin'), function () {

	Route::get('/admin', function(){
		return redirect()->route('admin.login.get');
	});

	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

	Route::get('reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

	Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.reset');

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

	Route::post('/login-post', 'Auth\AdminLoginController@login')->name('admin.login.post');

	Route::group(['middleware' => ['admin']], function () {

		//route for dashboard
		Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
		//route for logout
		Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
		//route for change-password
	});

});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login.get');
});

// Route::get('admin/change-password',function(){
// 	return view('admin.changepassword');
// });
Route::get('admin/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\AdminLoginController@login')->name('admin.login');

Route::post('admin/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');
Route::get('admin/password/reset/{token?}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get('admin/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout');

Route::post('admin/password/reset-password', 'Admin\Auth\ResetPasswordController@reset')->name('password.reset.post.password');

Route::get('/products/export','Admin\ProductController@exceltoexport')->name('products.export');
Route::post('notifications/names','Admin\NotificationController@getName')->name('get.name.notification');
Route::post('banners/names','Admin\BannerController@getName')->name('get.name.banner');
Route::get('admin/category/categoryorder','Admin\CategoryController@CategoryOrder')->name('category.order.get');
Route::get('admin/brand/brandorder','Admin\BrandController@BrandOrder')->name('brand.order.get');
Route::get('admin/banner/bannerorder','Admin\BannerController@BannerOrder')->name('banner.order.get');
Route::get('admin/products/suggetion','Admin\ProductController@CollectionSuggetion')->name('products.collection.suggetion');
Route::get('admin/product/suggetion/{id}','Admin\ProductController@CollectionSuggetionEdit')->name('products.suggetion.update');

Route::get('dealer/reset','Admin\UserController@ResetApiViewFile')->name('dealer.reset');
Route::post('api/reset/password','Admin\UserController@ApiResetPassword')->name('dealer.reset.password');

Route::group(['namespace'=>'Admin','prefix'=>'admin','middleware'=>'admin'],function(){
Route::post('dealers/deactive/{id}','UserController@deActive')->name('dealers.deactive');
	Route::resource('/brands','BrandController');
	Route::post('brands/delete','BrandController@delete')->name('brands.delete');
	Route::post('brand/order','BrandController@Order')->name('brand.order');	

	Route::resource('/category','CategoryController');
	Route::post('category/delete','CategoryController@delete')->name('category.delete');
	Route::post('category/order','CategoryController@Order')->name('category.order');

	Route::resource('/products','ProductController',['except'=>'update']);
	Route::post('/products/delete','ProductController@delete')->name('products.delete');
	Route::post('/products/update/{id}','ProductController@update')->name('products.update');
	Route::post('/products/category','ProductController@getCategory')->name('products.getcategory');
	Route::post('/products/image','ProductController@deleteImage')->name('delete.image');
	Route::post('/products/multipleimage','ProductController@UploadImage')->name('upload.url');
	Route::post('/products/size','ProductController@getSize')->name('products.getsize');	

	Route::post('/orders/{id}','OrderController@update')->name('orders.update');
	Route::post('/orders/store/invoice','OrderController@invoiceStore')->name('orders.store.invoice');
	Route::get('/orders/cancel','OrderController@OrderCancel')->name('orders.cancel');

	Route::resource('/orders','OrderController',['except'=>'update']);
	Route::post('/orders/delete','OrderController@delete')->name('orders.delete');
	Route::post('/orders/store/city','OrderController@getCity')->name('orders.getcity');
	Route::post('/orders/store/shippingcity','OrderController@getShippingCity')->name('orders.shippingcity');
	Route::post('/orders/store/getproductdata', 'OrderController@getProductData')->name('orders.getproductdata');
	Route::post('/orders/store/getdealerdata', 'OrderController@getDealerData')->name('orders.getdealerdata');
	Route::post('/orders/store/size','OrderController@getSize')->name('orders.getsize');

	Route::post('/user-plan/store','UserPlanController@store')->name('user-plan.store');
	Route::post('/user-plan/update/{id}','UserPlanController@update')->name('user-plan.update');
	Route::resource('/user-plan','UserPlanController',['except'=>'store','update']);
	Route::post('/user-plan/delete','UserPlanController@delete')->name('user-plan.delete');
	Route::post('/user-plan/category','UserPlanController@getCategory')->name('user-plan.getcategory');
	Route::post('/user-plan/product','UserPlanController@getProduct')->name('user-plan.getproduct');

	Route::resource('/coupons','CoupanCodeController');
	Route::post('/coupons/delete','CoupanCodeController@delete')->name('coupons.delete');
	// Route::post('/coupans/category','CoupanCode@getCategory')->name('coupans.getcategory');

	Route::resource('/color','ColorController');
	Route::post('color/delete','ColorController@delete')->name('color.delete');

	Route::resource('/size','SizeController');
	Route::post('size/delete','SizeController@delete')->name('size.delete');

	Route::resource('/pages','StaticPageController');
	Route::post('pages/delete','StaticPageController@delete')->name('pages.delete');


	Route::resource('/shipment','ShipmentController');
	Route::post('shipment/delete','ShipmentController@delete')->name('shipment.delete');

	Route::resource('/notifications','NotificationController');
	Route::post('notifications/delete','NotificationController@delete')->name('notifications.delete');

	Route::resource('/banners','BannerController');
	Route::post('banner/order','BannerController@Order')->name('banner.order');	
	Route::post('banners/delete','BannerController@delete')->name('banners.delete');
	

	Route::get('/dealers/view/{id}','UserController@view')->name('dealers.view');
	Route::resource('/dealers','UserController',['except'=>'show']);

	Route::get('/pdf','PdfController@downloadpdf')->name('pdf.get');

	Route::resource('/sales-person','SalesPersonController');
	Route::post('/sales-person/delete','SalesPersonController@delete')->name('sales-person.delete');
	Route::resource('/reports','ReportController');

	Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth:admin']], function () {

			Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
			Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
	});
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $table = "users";
    protected $fillable = ['id','type','user_plan_id','firstname','lastname','state','gstno','mobile','area','email','password','status','pincode','city','state','address','notification_id','company_name','created_at'];

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   protected $fillable = [
        'firstname','lastname','email','address','department','salary', 'password','status','phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use App\Models\User;
use App\Models\UserPlan;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserPasswordRequest;
use Mail;
use Illuminate\Support\Facades\Input;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            $where_str    = "1 = ?";
            $where_params = array(1); 

            if (!empty($request->input('sSearch')))
            {
                $search     = $request->input('sSearch');
                $where_str .= " and (firstname like \"%{$search}%\""
                . " or email like \"%{$search}%\""
                . " or mobile like \"%{$search}%\""
                . " or gstno like \"%{$search}%\""
                . ")";
            }                                            

            $columns = ['updated_at','gstno','mobile','email','status',DB::raw('CONCAT(users.firstname, " ", users.lastname) AS name'),'id'];

            $companymaster_columns_count = User::select($columns)
            ->whereRaw($where_str, $where_params)
            ->where('type','!=','seller')
            ->count();

            $companymaster_list = User::select($columns)
            ->whereRaw($where_str, $where_params)
            ->where('type','!=','seller');

            if($request->get('iDisplayStart') != '' && $request->get('iDisplayLength') != ''){
                $companymaster_list = $companymaster_list->take($request->input('iDisplayLength'))
                ->skip($request->input('iDisplayStart'));
            }          

            if($request->input('iSortCol_0')){
                $sql_order='';
                for ( $i = 0; $i < $request->input('iSortingCols'); $i++ )
                {
                    $column = $columns[$request->input('iSortCol_' . $i)];
                    if(false !== ($index = strpos($column, ' as '))){
                        $column = substr($column, 0, $index);
                    }
                    $companymaster_list = $companymaster_list->orderBy($column,$request->input('sSortDir_'.$i));   
                }
            } 


            $companymaster_list = $companymaster_list->get();

            $response['iTotalDisplayRecords'] = $companymaster_columns_count;
            $response['iTotalRecords'] = $companymaster_columns_count;
            $response['sEcho'] = intval($request->input('sEcho'));
            $response['aaData'] = $companymaster_list->toArray();

            return $response;
        }
        return view('admin.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $new_id = explode('_', $id);
        // dd($new_id);
        $user_data = User::find($new_id[1]);
        $id = $user_data['id'];
        $status = $new_id[0];
        $user_plan = UserPlan::orderBy('user_plan','asc')->pluck('user_plan','id')->toArray();
        return view('admin.user.edit',compact('user_plan','id','status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        $request_data = $request->all();
        // dd('id');
        $user_data= User::find($id);

        Mail::send('admin.user.mail',[], function($message) use ($user_data) {
            $message->to($user_data['email'])->cc('Maayaa@maayaaclothing.com')->subject('Dealer Approved');

        });
        
        $status = '0';
        if($request_data['status'] == 0){
            $status = '1';
        }
        // dd($request_data['status']);
        // dd($status);
        $data = User::find($id);
        $data->status = $status;
        $data->type = $request_data['type'];
        $data->user_plan_id = $request_data['user_plan_id'];
        $data->save();
        if($request->save_button == 'save_new') 
        {
            return back()->with('message','Record added  Successfully')
            ->with('message_type','success');
        }
        return redirect()->route('dealers.index')->with('message','Record added Successfully')->with('message_type','success');
    }
    public function deActive($id){
        //dd('hi');
        $new_id = explode('_', $id);
        $status = '0';
        $data = User::find($new_id[1]);
        $data->status = $status;
        $data->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function view($id)
    {
        $user_data = User::where('id',$id)->first();
        //  dd($user_data);
        return view('admin.user.view',compact('user_data'));
    }

    public function ResetApiViewFile()
    {
        return view('apimail.app_reset_password');
    }

    public function ApiResetPassword(UserPasswordRequest $request)
    {
        $input = $request->all();
        //$password = bcrypt($input['password']);
        //$user = new User();
        $user_id = User::select('id','status')->where('email',$input['email'])->first();
        //dd($user_id);
        $user_email = User::where('email','=',$input['email'])->exists();
        if($user_email == true && $user_id['status'] == 1)
        {//dd('1');
            $data =User::where('id', $user_id['id'])->update(['password' => bcrypt($input['password'])]);
            //return toast('Your password reset Successfully.');
            return back()->with('message','Your password reset Successfully.')
            ->with('message_type','success');
        }
        else
        {
          //dd('2');
            return back()->with('message','Email address does not exists.')
            ->with('message_type','success');
        }
    }
}

resources/views/admin/user/edit.blade.php
<?= Form::open(['route'=>['dealers.update',$id],'role'=>'form','class'=>'m-0','files'=>true,'method'=>'PATCH','id'=>'form_data']) ?>
<input type="hidden" name="status" value="{{$status}}">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group @if($errors->has('type')) {{ 'has-error' }} @endif">
                                    <label>Dealer Type <sup class="text-danger">*</sup></label>
                                    <?=Form::select('type',['seller'=>'Sales Person','Company Name'=>'Company Name'],old('type'), ['class' => 'form-control type null_value_class','id' => 'type','placeholder'=>'Select Dealer Type']);?> 
                                    <span id="type_error" class="help-inline text-danger"><?= $errors->first('type') ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group  @if($errors->has('user_plan_id')) {{ 'has-error' }} @endif">
                            <label>Dealer Plan <sup class="text-danger">*</sup></label>
                            <?=Form::select('user_plan_id',$user_plan,old('user_plan_id'), ['class' => 'form-control null_value_class user_plan_id','id' => 'user_plan_id','placeholder'=>'Select User Plan']);?>
                            <span id="user_plan_id_error" class="help-inline text-danger"><?= $errors->first('user_plan_id') ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="text-right">
        <button type="button" name="save_button" value="save_exit" class="btn btn-primary btn-sm disabled-btn save_data" title="Save">Save</button>
            <a href="<?= route('dealers.index') ?>" class="btn btn-default btn-sm" title="Cancel">Cancel</a>
    </div>
<?= Form::close() ?>

<script src="<?= asset('backend/js/jquery.min.js') ?>"></script>
<script src="<?= asset('backend/js/jquery.form.min.js') ?>"></script>
<script type="text/javascript">  
    $('.save_data').click(function(e,ele){
        var token = "<?=csrf_token()?>";
        var id = "<?= $id?>";
        var viewurl = "{{ route('dealers.update',':id')}}";
        url = viewurl.replace(':id',id);
        $('#form_data').ajaxSubmit({
            url: url,
            type: 'POST',
            data: { "_token" : token},
            dataType: 'json',  
            beforeSubmit : function()
            {
                //$("[id$='_error']").empty();
            },          
            success : function(resp)
            { 
                $(".null_value_class").val("");
                toastr.success('Record added Successfully'); 
                location.href = "<?= route('dealers.index') ?>"
            },
            error : function(respObj){ 
                $.each(respObj.responseJSON, function(k,v){
                    $('#'+k+'_error').text(v);
                }); 
                $('#type_error').text(respObj.responseJSON.errors.type);
                $('#user_plan_id_error').text(respObj.responseJSON.errors.user_plan_id);
                //toastr.error('There was some error');
            }
        });
        return false;
    });
</script>

resources/views/admin/user/index.blade.php
@extends('admin.layout.layout')
@section('top_fixed_content')
<?=Html::style('backend/css/custome.css')?>
<nav class="navbar navbar-static-top">
    <div class="title">
        <h4><i class="fa fa-list"></i>Dealer Master</h4>
    </div>
    <div class="top_filter"></div>
</nav>
@stop
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body table-responsive">
                <table id="supplier_table" class="table table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Mobile No</th>
                            <th>GST</th>
                            <th>Approve/DisApprove</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            @include('admin.layout.overlay')
        </div>
    </div>
</div>
<div id="modal-consultant-profile" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body box no-border">
                <div id="modal-consultant-profile-info"></div>
                <!-- <div class="overlay" id="modal-consultant-profile-loader">
                    <i class="fa fa-spin fa-spinner"></i>
                </div> -->
            </div>
        </div>
    </div>
@stop
<!-- for error list show in model -->
@section('script')

<?=Html::script('backend/plugins/datatable/jquery.dataTables.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/datatable/dataTables.bootstrap.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/sweetalert/sweetalert.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/fnstandrow.js', [], IS_SECURE)?>
<?=Html::script('backend/js/delete_script.js', [], IS_SECURE)?>

<script type="text/javascript">
    $('#supplier_table').DataTable({
            "bProcessing": false,
            "bServerSide": true,
            "autoWidth": false,
            lengthMenu: [
                [ 10, 25, 50, 100,200,500],
                [ '10', '25', '50','100','200','500']
            ],
            "sAjaxSource": "<?= route('dealers.index')?>",
            "aaSorting": [ 1,"desc"],
            "aoColumns": [
            { mData:"updated_at",bSortable : false,sClass : 'text-center',sWidth:"16%",bVisible : false},
            { mData:"name",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"email",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"mobile",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"gstno",bSortable : true,sClass : 'text-center',sWidth:"16%"},
            { mData:"status",bSortable : false,sClass : 'text-center',sWidth:"15%",
                mRender: function(v, t, o) {

                            var editurl = "";
                            editurl = editurl.replace(':id',o['id']);

                            if(o['status'] == '0')
                            {
                                var act_html = "<div class='btn-group'>"
                                +"<label class='switch'><input type='checkbox' onClick='approve("+o['id']+","+o['status']+")' data-attr="+o['status']+" id='status' name='status' ><span class='slider round'></span></label>"
                                +"</div>"
                            }else{
                                var act_html = "<div class='btn-group'>"
                                +"<label class='switch'><input type='checkbox' onClick='approve("+o['id']+","+o['status']+")'  id='status' name='status' checked><span class='slider round'></span></label>"
                                +"</div>"
                            }
                            return act_html;
                        }
                    },
            {
            mData     : "id",
            sWidth    : "100px",
            sClass    : 'text-center',
            bVisible  : true,
            bSortable : false,
            mRender   : function (v, t, o) {

                var editurl = "";
                editurl = editurl.replace(':id',o['id']);
                    var act_html = "<div class='btn-group'>"

                    +"<button type='button' class='btn btn-default btn-xs' onClick='view("+o['id']+")'><i class='fa fa-search-plus' title='Edit Record'></i></button>"    
                    +"</div>";
                return act_html;
              }
                },
                    
            ],
            fnPreDrawCallback : function() { $("div.overlay").css('display','flex'); },
            fnDrawCallback : function (oSettings) {
                $("div.overlay").hide();
            },
        });
</script>

<script type="text/javascript">

    function approve(id,status)
    {
        var new_id = status +'_'+ id;
        if(status == '0'){
            $('#modal-consultant-profile-loader').show();
            $('#modal-consultant-profile').modal('show');

            var viewurl = "{{ route('dealers.edit',':id')}}";
            viewurl = viewurl.replace(':id',new_id);

            $.get(viewurl, function(resp) {
                $('#modal-consultant-profile-loader').hide();
                $('#modal-consultant-profile-info').html(resp);
            });
        }else{
            var viewurl = "{{ route('dealers.deactive',':id')}}";
            viewurl = viewurl.replace(':id',new_id);
            $.ajax({
                url : viewurl,
                type : 'POST',
                data : {'_token':"{{csrf_token()}}"},
                success : function(response, textStatus, jqXhr) {
                    console.log("Venue Successfully Patched!");
                    location.reload();
                }
            });
        }
        
    }

    function view(id)
    {
        $('#modal-consultant-profile-loader').show();
            $('#modal-consultant-profile').modal('show');

            var viewurl = "{{ route('dealers.view',':id')}}";
            viewurl = viewurl.replace(':id',id);
            $.get(viewurl, function(resp) {
                $('#modal-consultant-profile-loader').hide();
                $('#modal-consultant-profile-info').html(resp);
        });
    }
</script>
@include('admin.layout.alert')
@stop

resources/views/admin/user/mail.blade.php
<!DOCTYPE html>
<html>
  <head></head>
  <body style="font-family: 'Muli', sans-serif;">
    <div style="text-align: center;width: 100%;font-family: open sans;max-width: 580px;float: none;margin: 0 auto;border: 1px solid #686868 ;padding-top: 30px;">
      <div style="padding: 0px;text-align: center;display: inline-block;float: left;width: 100%;">
        <div style="margin-bottom: 20px;"><img src="<?= LOCAL_IMAGE_PATH.'maya-logo.png' ?>" alt="logo" style="height: 80px"></div>
        <div>
          <div style="padding: 0 20px;">
            <div>
              <div style="font-size: 16px;margin-bottom: 10px;">THANK YOU FOR CONNECTING WITH US. WELCOME TO MAAYAA CLOTHING APP.</div>
            </div>
          </div>
        </div>
        <div style="text-align: left">
          <div style="padding:  20px;">
            <div>
              <div style="font-size: 20px;margin-bottom: 10px;">Thanks for dealing with us Team MAAYA
                <br>
                <div style="margin-bottom: 20px;"><img src="<?= LOCAL_IMAGE_PATH.'maya-logo.png' ?>" alt="logo" style="height: 40px"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div>
          <div style="background-color: #333;color: #fff;font-size: 20px;width: 100%;display: inline-block;box-sizing: border-box;">
            <div style="padding:10px  20px;">
              <div>Stay In Touch ! Find Us On </div>
              <div>
                <a href="www.facebook.com/maayaaclothingofficial"><img src="<?= LOCAL_IMAGE_PATH.'facebook-icon.png' ?>" style="margin:5px;"></a>
                <a href="www.youtube.com/user/MrVipulchheda/channels"><img src="<?= LOCAL_IMAGE_PATH.'youtube-icon.png' ?>" style="margin:5px;"></a>
                <a href="www.instagram.com/maayaaclothingofficial/"><img src="<?= LOCAL_IMAGE_PATH.'instagram-icon.png' ?>" style="margin:5px;"></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>